---
- name: Configuring DNS server (BIND/named) on Rocky Linux 9
  hosts: dns_servers
  become: true
  gather_facts: true
  roles:
    - dns_bind

- name: Configuring DHCP server (dhcpd) on Rocky Linux 9
  hosts: dhcp_servers
  become: true
  gather_facts: true
  roles:
    - dhcpd
