---
- name: Configurar servidor DNS + DHCP consolidado (Rocky 9)
  hosts: dns_dhcp_servers
  become: true
  roles:
    - dns_bind
    - dhcpd

- name: Convertir la VM restante en cliente DHCP (Rocky 9)
  hosts: dhcp_clients
  become: true
  roles:
    - dhcpd_client
