# Servidor único: DHCP + DNS
[dns_dhcp_servers]
dnsdhcp01 ansible_host=192.168.56.107

# VM que pasa de servidor(a) a cliente DHCP
# IMPORTANTE: usa aquí la IP ESTATICA ACTUAL del cliente para que Ansible
# pueda conectarse por SSH ANTES de cambiarla a DHCP.
[dhcp_clients]
client1 ansible_host=192.168.56.109   # EJEMPLO: IP estática actual del cliente

[dns_dhcp_servers:vars]
ansible_user=ansible

[dhcp_clients:vars]
ansible_user=ansible
