---
dhcp_interface: ""
dhcp_domain_name: "{{ domain_name }}"
dhcp_domain_name_servers: []
dhcp_default_lease_time: 600
dhcp_max_lease_time: 7200
dhcp_subnets: []
dhcp_reservations: []
manage_firewalld: true
